version: '3'
services:
  validator:
    image: 0xsachink/validator:0.0.1-rc3
    ports:
      - 8080:8080
    volumes:
      - /Users/sachin/sockets/tappd.sock:/var/run/tappd.sock
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:*
      - WISE_API_BASE_URL=https://api.wise.com
      - LOG_LEVEL=debug
